### PR TITLE
Use credentialed requests for password updates

### LINKED ISSUE #199: Rails 6 Upgrade: Updating password from PFE mentions returns error that user is not signed in
Errors when updating password from Profile Settings Page from Rails 6 on Staging. See image below. 

When changing password via Settings, error `Error: You need to sign in or sign up before continuing.` comes from the `PUT` request 

Screen Shot 2023-02-20 at 10 32 29 AM

Mentioned in PR: https://github.com/zooniverse/panoptes/pull/4114

`lib/auth.js` still uses some calls to `apiClient.put` and `apiClient.post`, which weren’t converted over to `makeCredentialHTTPRequest` in #121. Converting them will probably close this.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Swap `apiClient.put` for `makeCredentialHTTPRequest` in `auth.changePassword` and `auth.resetPassword`.

This should allow those client methods to work even when the client and the API are not on the same origin eg. when using the staging API.

Closes #199.

I've set up https://github.com/zooniverse/Panoptes-Front-End/pull/6436 to test this branch, so you can try out the changes on https://pr-6436.pfe-preview.zooniverse.org.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
When I try to change my password on this branch, it still errors but now the error is a 405 response. The API doesn't allow PUT for cross-domain requests, it seems.

Here are the [HTTP 405 kittens](https://httpcats.com/405).

**Comment by eatyourgreens** [comment]
I'm happy to leave this bug in the client for the time being, unless there's a burning need to get password reset working on staging.

File: lib/auth.js [hunk 1]
```diff
@@ -254,7 +254,7 @@ const authClient = new Model({
             },
           };
 
-          return apiClient.put('/../users', data, config.jsonHeaders)
+          return makeCredentialHTTPRequest('PUT', '/../users', data, config.jsonHeaders)
```
Comment (camallen) [inline lib/auth.js:257]: We need to supply the API domain + path URL here as this defaults to the window origin which isn't the API host. 
```suggestion
          const url = config.host + '/users';
          return makeCredentialHTTPRequest('PUT', 'url', data, config.jsonHeaders)
```

**Review by camallen — COMMENTED** [review]
This code now requests a PUT `https://pr-6436.pfe-preview.zooniverse.org/users` end point which isn't the API. This is a proxy to to the blob store and hence we get the `x-ms-error-code | UnsupportedHttpVerb` header response / `405
Method Not Allowed` HTTP response.

The `makeCredentialHTTPRequest` needs to provide an API host and path URL to work correctly, not just a path. 

Finally I don't think we need the credentialed request for password reset request but we most likely do for the others.

File: lib/auth.js [hunk 2]
```diff
@@ -297,7 +297,7 @@ const authClient = new Model({
         },
       };
 
-      return apiClient.put('/../users/password', data, config.jsonHeaders);
+      return makeCredentialHTTPRequest('PUT', '/../users/password', data, config.jsonHeaders);
```
Comment (camallen) [inline lib/auth.js:300]: This will also need the API host domain + path URL, avoid defaulting to the window origin.

File: lib/auth.js (hunk 1 above)
Comment (eatyourgreens) [reply lib/auth.js:257]: Good catch!

File: lib/auth.js [hunk 3]
```diff
@@ -282,7 +282,7 @@ const authClient = new Model({
         },
       };
 
-      return apiClient.post('/../users/password', data, config.jsonHeaders);
+      return makeCredentialHTTPRequest('POST', '/../users/password', data, config.jsonHeaders);
```
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply lib/auth.js:285]: Good point.

**Comment by eatyourgreens** [comment]
I've made those changes and updated the staging branch. Changing your password works now, even if you aren't on the same domain as the API.
https://pr-6436.pfe-preview.zooniverse.org/

**Comment by eatyourgreens** [comment]
I’ll get these changes out soonish as 5.2.3.
